### ISSUE TITLE
Poor performance on KITTI

### ISSUE THREAD

**Issue by LimHyungTae** [ethz-asl/phaser#55]
Hope you are doing well.

I tested Phaser, but it shows rather poor performance on KITTI 00.

I believe that's about the parameter setting; I used the parameters that you provided as follows:
REST=$@
  --v=2 \
  --alsologtostderr=1 \
  --phaser_core_spherical_bandwidth=160 \
  --phaser_core_spherical_low_pass_lower_bound=000 \
  --phaser_core_spherical_low_pass_upper_bound=10000 \
  --phaser_core_spherical_zero_padding=10 \
  --phaser_core_spatial_n_voxels=201 \
  --phaser_core_spatial_discretize_lower=-50 \
  --phaser_core_spatial_discretize_upper=50 \
  --phaser_core_spatial_low_pass_lower_bound=85 \
  --phaser_core_spatial_low_pass_upper_bound=115 \
  --phaser_core_spatial_zero_padding=0 \
  --gaussian_peak_neighbors=0 \
  --bingham_peak_neighbors=0 \
  --z_score_filter_threshold=0.01 \
  --z_score_lag_max=3 \
  --z_score_threshold=3.0 \
  --phaser_pre_enable_geometric_cloud_segmentation=false \
  $REST

But, its relative pose is not precise as shown in the below figure:

![image](https://user-images.githubusercontent.com/35317311/121768425-16547280-cb99-11eb-9385-8fcb377d75f5.png)

why does It happen? Thanks in advance.

**Comment by LimHyungTae** [comment]
On, please note that I revised the phaser_core_driver node to load KITTI sequences automatically. Thanks!

**Comment by LBern** [comment]
Some points here: 
 * PHASER is mainly intended for global alignment problems. This is more a local problem. 
 * The intensity channel of KITTI has a *low SNR* and thus is quite hard for PHASER
 * These settings are used for an Ouster OS0 - 128

Overall, the signals that you provided might not be reasonably good for the correlations. Remember, It always gives you the alignment that is best fitting one given the two signals.

**Comment by LimHyungTae** [comment]
The comments really help me! Thank you Ibern! *^^*
