### ISSUE TITLE
Question about Spherical Fourier Analysis

### ISSUE THREAD

**Issue by kidpaul94** [ethz-asl/phaser#56]
Hi, thank you for the great work!

I wonder how you chose weight for calculating each Fourier coefficient?

**Comment by LBern** [comment]
For the quadrature weights, PHASER uses S2Kit by Kostelec and Rockmore.
You can have a look at [this code](https://github.com/ethz-asl/phaser/blob/master/phaser_core/lib/SOFT/makeweights.c).

Reference: 

> Kostelec, P. J., & Rockmore, D. N. (2008). FFTs on the rotation group. Journal of Fourier analysis and applications, 14(2), 145-179.

**Comment by kidpaul94** [comment]
Thank you!
