### ISSUE TITLE
Appropriate parameters for 64 channel LiDAR?

### ISSUE THREAD

**Issue by LimHyungTae** [ethz-asl/phaser#57]
Hello there, I'm continuously interested in your research,

and I hope to know the best parameters for 64 channel LiDAR for your fantastic algorithm.

Unfortunately, I didn't find the optimal parameters in KITTI and it took a long time so I'd like to ask you for some advice.

Thank you in advance!

**Comment by LimHyungTae** [comment]
The reason why I ask you is that your parameters are not directly matched to those in the paper :(.

**Comment by LBern** [comment]
What particular values have you tried? What FoV are you using for the spatial correlation?
A spherical BW of ~100  and a spatial BW of 5+ is good enough in most cases. 
I'd suspect that it is not a problem of the parameters but rather the data might not be optimal for a correlation.

Which channels do you feed in? The intensity channel on KITTI can have a large discrepancy between two scenes. 
Similar, only taking the range values does not yield good results as shown in the paper. 
What is the distance between source and target? How much overlap? 

One last thing:
Obviously, Phaser has the same downside as a typical point-to-point error without outlier rejection. Consequently, points on the ground can have a high influence on the correlation. This should be kept in mind.
