### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by eduardohenriquearnold** [ethz-asl/phaser#58]
I've been trying to build the package as instructed in `README.md` without success.

I have tried the following:

1. Installing dependencies as per `README.md`
2. Cloning the GH repo at ~/phaser
2. From `~/phaser`, running `wstool init &&  wstool merge dependencies.rosinstall &&  wstool update`
3. From `~/phaser`, running `catkin build phaser_ros`

This results in the error `[build] No packages were found in the source space`

Then I deleted `~/phaser`, cloned it again, but initialised the catkin environment within `~/phaser/phaser_ros`
This was the output:
```
$ catkin build phaser_ros
------------------------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/melodic
Workspace:                   ~/phaser/phaser_ros
------------------------------------------------------------------------------------------
Build Space:        [exists] ~/phaser/phaser_ros/build
Devel Space:        [exists] ~/phaser/phaser_ros/devel
Install Space:      [unused] ~/phaser/phaser_ros/install
Log Space:         [missing] ~/phaser/phaser_ros/logs
Source Space:       [exists] ~/phaser/phaser_ros/src
DESTDIR:            [unused] None
------------------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
------------------------------------------------------------------------------------------
[build] No packages were found in the source space '~/phaser/phaser_ros/src'
[build] Given package 'phaser_ros' is not in the workspace
```

Can you please provide a more detailed guide on the installation and building process? For example, where should the catkin environment be created w.r.t. the cloned GH repo? What does the project tree looks like? Thanks

**Comment by LBern** [comment]
It seems that you have created a quite odd catkin workspace here. Perhaps, familiarize yourself a bit with [workspaces](http://wiki.ros.org/catkin/workspaces) and [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/).

Anyway, for a quick tutorial: 
```
mkdir test_ws
cd test_ws
mkdir src
catkin init --workspace .
catkin config -DCMAKE_BUILD_TYPE=Release
cd src
git clone....
```
