### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by maxtomCMU** [ethz-asl/phaser#59]
When I try to build this project, I first meet the following error:
`math_functions.hpp not found when using CUDA with Eigen`

Then I fix this by creating a symlink from `cuda/include/math_functions.hpp` to `cuda/include/crt/math_functions.hpp` fixed the issue.
However, I meet the following problem now:

`
Errors     << phaser_core:make /home/maxtom/codespace/ph_ws/logs/phaser_core/build.make.001.log                                                        
In file included from /usr/include/eigen3/Eigen/Core:42:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/maxtom/codespace/ph_ws/src/phaser/phaser_core/include/phaser/backend/correlation/base-spatial-correlation.h:7,
                 from /home/maxtom/codespace/ph_ws/src/phaser/phaser_core/include/phaser/backend/correlation/spatial-correlation-cuda.h:4,
                 from /home/maxtom/codespace/ph_ws/src/phaser/phaser_core/src/backend/correlation/spatial-correlation-cuda.cu:4:
/usr/local/cuda/include/math_functions.hpp:54:2: warning: #warning "crt/math_functions.hpp is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "crt/math_functions.hpp is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
  ^~~~~~~
In file included from /usr/local/cuda/include/cuda_runtime.h:115:0,
                 from <command-line>:0:
/usr/local/cuda/include/crt/common_functions.h:74:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
/usr/local/cuda/include/crt/common_functions.h:74:24: note: in definition of macro ‘__CUDACC_VER__’
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/include/crt/common_functions.h:74:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
/usr/local/cuda/include/crt/common_functions.h:74:24: note: in definition of macro ‘__CUDACC_VER__’
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/include/crt/common_functions.h:74:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
/usr/local/cuda/include/crt/common_functions.h:74:24: note: in definition of macro ‘__CUDACC_VER__’
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/include/crt/common_functions.h:74:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
/usr/local/cuda/include/crt/common_functions.h:74:24: note: in definition of macro ‘__CUDACC_VER__’
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/include/crt/common_functions.h:74:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
/usr/local/cuda/include/crt/common_functions.h:74:24: note: in definition of macro ‘__CUDACC_VER__’
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at phaser_core_cuda_lib_generated_spatial-correlation-cuda.cu.o.cmake:220 (message):
  Error generating
  /home/maxtom/codespace/ph_ws/build/phaser_core/CMakeFiles/phaser_core_cuda_lib.dir/src/backend/correlation/./phaser_core_cuda_lib_generated_spatial-correlation-cuda.cu.o

make[2]: *** [CMakeFiles/phaser_core_cuda_lib.dir/src/backend/correlation/phaser_core_cuda_lib_generated_spatial-correlation-cuda.cu.o] Error 1
make[1]: *** [CMakeFiles/phaser_core_cuda_lib.dir/all] Error 2
make: *** [all] Error 2
cd /home/maxtom/codespace/ph_ws/build/phaser_core; catkin build --get-env phaser_core | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.......................................................................................................................................................
Failed     << phaser_core:make                [ Exited with code 2 ]                                                                                   
Failed    <<< phaser_core                     [ 0.3 seconds ]                                                                                          
Abandoned <<< phaser_ros                      [ Unrelated job failed ]                                                                                 
[build] Summary: 13 of 15 packages succeeded.                                                                                                          
[build]   Ignored:   None.                                                                                                                             
[build]   Warnings:  None.                                                                                                                             
[build]   Abandoned: 1 packages were abandoned.                                                                                                        
[build]   Failed:    1 packages failed.                                                                                                                
[build] Runtime: 2.1 seconds total.           
`

**Comment by LBern** [comment]
Yes, I admit setting this up with CUDA is a bit of a hassle. 

As far as I remember, I believe that I removed the line throwing the error message from `/usr/local/cuda/include/cuda_runtime.h`. 
At least I also don't see it anymore on my local machine.
