### ISSUE TITLE
run: wstool update,have problem

### ISSUE THREAD

**Issue by vincenzo0603** [ethz-asl/phaser#61]
Cloning into '/home/vincent/catkin_ws/catkin_simple'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository

no permission to access remote repository

**Comment by jalexvig** [comment]
@vincenzo0603 https://github.com/ethz-asl/phaser/pull/63 should fix this

**Comment by LBern** [comment]
fixed by #63
