### ISSUE TITLE
[rosrun] Couldn't find executable named phaser_core_driver

### ISSUE THREAD

**Issue by OliverShaoPT** [ethz-asl/phaser#62]
Thanks for sharing your great work!  I try to run the test following " ./phaser_share/run_build_tests" command, but rosrun reports error: "[rosrun] Couldn't find executable named phaser_core_driver". 

Additional,  it can pass all unit tests using "./phaser_share/run_build_tests".  What did I miss?
![Screenshot from 2022-06-01 16-32-29](https://user-images.githubusercontent.com/37506826/171376646-fed02426-b2a2-4a3e-8c21-a5d2d4d38607.png)
?

**Comment by LBern** [comment]
fixed by #65
