### ISSUE TITLE
Catkin install

### ISSUE THREAD

**Issue by jalexvig** [ethz-asl/phaser#64]
Hi, interested in using this code however it seems like there is a fair amount of configuration required. A dockerfile would be handy (e.g. it would help with open issues https://github.com/ethz-asl/phaser/issues/62 and https://github.com/ethz-asl/phaser/issues/61). Happy to PR it but can't get this working.

The `catkin build phaser_ros` line errors with `#15 0.593 [build] Error: Unable to find source space '/phaser/src'`.

Not familiar with catkin. What am I missing here?

Dockerfile I'm using:

```
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt update
RUN apt install -y doxygen autotools-dev \
    dh-autoreconf libboost-all-dev python-setuptools git g++ cppcheck \
    libgtest-dev python-git pylint \
    python-termcolor liblog4cplus-dev cimg-dev python-wstool python-pip \
    clang-format-6.0 curl \
    libpcl-dev libnlopt-dev

RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" | tee /etc/apt/sources.list.d/ros-latest.list
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt update
RUN apt install -y ros-melodic-pcl-conversions

RUN pip install -U catkin_tools

RUN git clone https://github.com/jalexvig/phaser.git

WORKDIR phaser

RUN wstool init && wstool merge dependencies.rosinstall && wstool update

RUN catkin build phaser_ros

RUN apt install -y zsh vim
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true

CMD [ "zsh" ]
```

**Comment by LBern** [comment]
I think you are mostly there. 
To use catkin as a build system, you'd need to create a local workspace (https://catkin-tools.readthedocs.io/en/latest/quick_start.html). 

In your dockerfile you'd need to add something like:
```
WORKDIR /usr/home/ws
RUN catkin init --workspace .
RUN catkin config --merge-devel
```

Cloning of phaser happens in `/usr/home/ws/src/phaser` which should then be fine to build.
You might need, however, to source `/opt/ros/melodic/setup.bash` at some point for the building.

**Comment by jalexvig** [comment]
Okay updated per your input and am getting another error. I've seen this issue raised a couple times across ASL projects (e.g. https://github.com/ethz-asl/mav_trajectory_generation/issues/79, https://github.com/ethz-asl/geodetic_utils/issues/33) but the solutions haven't worked. `catkin_simple` does exist in the WS (per the wstool install) but looks like the cmake config is not found. What is the best way of fixing this?

```Errors     << catkin_simple:cmake /catkin_ws/logs/catkin_simple/build.cmake.000.log
CMake Error at /catkin_ws/src/catkin_simple/CMakeLists.txt:4 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.```

Updated dockerfile for reference:

```
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt update
RUN apt install -y doxygen autotools-dev \
    dh-autoreconf libboost-all-dev python-setuptools git g++ cppcheck \
    libgtest-dev python-git pylint \
    python-termcolor liblog4cplus-dev cimg-dev python-wstool python-pip \
    clang-format-6.0 curl \
    libpcl-dev libnlopt-dev zsh vim

RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true

RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" | tee /etc/apt/sources.list.d/ros-latest.list
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt update
RUN apt install -y ros-melodic-pcl-conversions

RUN apt install -y python-catkin-tools

RUN mkdir catkin_ws
WORKDIR /catkin_ws

RUN mkdir src
RUN git clone https://github.com/jalexvig/phaser.git src/phaser

RUN catkin init
RUN catkin config --merge-devel

RUN wstool init && wstool merge src/phaser/dependencies.rosinstall && wstool update

RUN catkin build phaser_ros

CMD [ "zsh" ]
```

**Comment by LBern** [comment]
I added some deployment scripts to the main repo (https://github.com/ethz-asl/phaser/tree/master/phaser_deploy). You can check those out and hopefully, they'll resolve your issues. Let me know how it goes.

**Comment by jalexvig** [comment]
@LBern Hmm, this still doesn't work for me. Does it work for you? I get the following error:

```
#21 463.4 Starting >>> phaser_common
_______________________________________________________________________________[phase...
#21 590.0 Errors << phaser_common:make /usr/home/ws/logs/phaser_common/build.make.000.log
#21 590.0 c++: internal compiler error: Killed (program cc1plus)
#21 590.0 Please submit a full bug report,
#21 590.0 with preprocessed source if appropriate.
#21 590.0 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#21 590.0 make[2]: *** [CMakeFiles/phaser_common_lib.dir/src/model/point-cloud.cc.o] Error 4
#21 590.0 make[2]: *** Waiting for unfinished jobs....
#21 590.0 make[1]: *** [CMakeFiles/phaser_common_lib.dir/all] Error 2
#21 590.0 make: *** [all] Error 2
#21 590.0 cd /usr/home/ws/build/phaser_common; catkin build --get-env phaser_common | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
#21 590.0 Failed << phaser_common:make               [ Exited with code 2 ]
#21 590.1 Failed <<< phaser_common                   [ 2 minutes and 6.6 seconds ]
#21 590.1 Abandoned <<< phaser_pre                      [ Unrelated job failed ]
#21 590.1 Abandoned <<< phaser_viz                      [ Unrelated job failed ]
#21 590.1 Abandoned <<< phaser_core                     [ Unrelated job failed ]
#21 590.1 [build] Summary: 10 of 14 packages succeeded.
#21 590.1 [build] Ignored: 1 packages were skipped or are blacklisted.
#21 590.1 [build] Warnings: 5 packages succeeded with warnings.
#21 590.1 [build] Abandoned: 3 packages were abandoned.
#21 590.1 [build] Failed: 1 packages failed.
#21 590.1 [build] Runtime: 9 minutes and 48.8 seconds total.
#21 590.1 [build] Note: Workspace packages have changed, please re-source setup files to use them.
------
executor failed running [/bin/bash -c ../compile.sh]: exit code: 1
Finished building the images. Cleaning up.
```

**Comment by jalexvig** [comment]
@LBern if this works for you, can you just put an image up on dockerhub?

**Comment by LBern** [comment]
Not particularly sure why it is not getting the fftw3 library in the docker image. I added the PLYs and the missing deps to the deployment scripts.
